archetype:
  name: java-lib
  version: 0.1-SNAPSHOT
  organization: org.m410.fabricate.javalib

bundles:
  - name: fab-share
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-share/target/fab-share-0.1-SNAPSHOT.jar
  - name: java-lib
    org: org.m410.fabricate.garden
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-java-lib-project/target/fab-java-lib-project-0.1-SNAPSHOT.jar

build:
  cacheDir: .fab
  defaultEnvironment: development
  defaultCommand: build
  lang: java
  langVersion: "1.8"
  compilerArgs: -ea
  targetDir: target
  webappDir: webapp
  sourceDir: src/java
  sourceOutputDir: target/classes
  resourceDir: src/resources
  testDir: test/java
  testOutputDir: target/test-classes
  testResourceDir: test/resources
  vcs:
  packageSource: false
  packageDocs: false
  packageName:
