archetype:
  name: garden
  version: 0.1-SNAPSHOT
  organization: org.m410.fabricate

bundles:
  - name: fab-share
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-share/target/fab-share-0.1-SNAPSHOT.jar
  - name: fab-java-garden-project
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-java-garden-project/target/fab-java-garden-project-0.1-SNAPSHOT.jar
  - name: fab-war
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-war/target/fab-war-0.1-SNAPSHOT.jar
  - name: fab-junit
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-junit/target/fab-junit-0.1-SNAPSHOT.jar
  - name: fab-java-compiler
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-java-compiler/target/fab-java-compiler-0.1-SNAPSHOT.jar
  - name: fab-dependencies
    org: org.m410.fabricate
    version: 0.1-SNAPSHOT
    url: file:/Users/m410/Projects/fabricate/fab-dependencies/target/fab-dependencies-0.1-SNAPSHOT.jar

dependencies:
  - { scope: compile, org: com.google.code.gson, name: gson, rev: 2.2.4 }
  - { scope: compile, org: org.m410.garden, name: garden, rev: 0.2.0-SNAPSHOT }
  - { scope: compile, org: commons-beanutils, name: commons-beanutils, rev: 1.9.0 }
  - { scope: compile, org: org.apache.commons, name: commons-lang3, rev: 3.2.1 }

build:
  defaultEnvironment: development
  defaultCommand: make
  lang: java
  langVersion: "1.8"
  compilerArgs: -ea
  targetDir: target
  webappDir: webapp
  sourceDir: src/java
  sourceOutputDir: target/classes
  resourceDir: src/resources
  testDir: test/java
  testOutputDir: target/test-classes
  testResourceDir: test/resources
  vcs: 
  packageSource: false
  packageDocs: false
  packageName:

deploy:

publish:

persistence:

modules:

logging:


