cache: "~/.fab"

repositories:
- id: m410
  url: "http://repo.m410.org/content/repositories/releases"
- id: maven-central
  url: "http://repo.maven.apache.org/maven2"
- id: m410-snapshot
  url: "http://repo.brzy.org/content/repositories/snapshots"

archetypes:
- name: garden
  org: org.m410.fabricate
  type: project # or module
  description: A java web mvc framework that produces a war
  homepage: http://m410.org
  documentation: http://m410.org
  license: Apache 2
  dist: http://someurl.com
  hash: asdffdasasdffdsa
  versions:
  - version: "0.2"
    release_date: 2016-01-01



- name: java-lib
  org: org.m410.fabricate
  description: A basic project that produces a jar
  homepage: http://m410.org
  license: Apache 2
  versions:
  - version: "0.2"
    release_date: 2016-01-01
