/*
 * Copyright 2001-2005 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.m410.fab.garden;

import org.m410.fab.builder.BuildContext;
import org.m410.fab.builder.Task;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Collection;
import java.util.stream.Collectors;

/**
 * Generates a web.xml and configuration file from the source.
 * http://docs.codehaus.org/display/MAVENUSER/Mojo+Developer+Cookbook#MojoDeveloperCookbook-Foraccessingartifactsandrepositories
 *
 * @author Michael Fortin
 */
public final class WebXmlTask implements Task {

    // todo should be generated by the application like the persistence and orm files.

    private static final String xml =
            "<web-app xmlns=\"http://xmlns.jcp.org/xml/ns/javaee\"\n" +
            "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
            "         xsi:schemaLocation=\"http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd\"\n" +
            "         version=\"3.1\"\n" +
            "         metadata-complete=\"true\">\n" +
            "  <context-param>\n" +
            "    <param-name>m410-env</param-name>\n" +
            "    <param-value>{{env}}</param-value>\n" +
            "  </context-param>\n" +
            "  <listener>\n" +
            "    <listener-class>org.m410.garden.application.ApplicationContextListener</listener-class>\n" +
            "  </listener>\n" +
            "</web-app>";


    @Override
    public String getName() {
        return "web-xml";
    }

    @Override
    public String getDescription() {
        return "Generate the web.xml configuration file";
    }

    @Override
    public void execute(BuildContext context) throws Exception {

        Collection<File> mavenProject = Arrays.asList(
                context.getClasspath()
                        .get("compile")
                        .split(System.getProperty("path.separator")))
                .stream()
                .map(File::new)
                .collect(Collectors.toList());

        context.cli().debug("artifacts =" + mavenProject    );
        initWebXml(context.environment());
        moveM410Config();
    }

    private void moveM410Config() throws IOException {
        Path source = Paths.get("configuration.m410.yml");
        Path target = Paths.get("target/classes/configuration.m410.yml");

        if(!target.toFile().exists())
            Files.copy(source, target);
    }

    private void initWebXml(String envName) throws IOException {
        File outputDir = FileSystems.getDefault().getPath("src/main/webapp/WEB-INF").toFile();

        if(!outputDir.exists() && !outputDir.mkdirs())
            throw new RuntimeException("Could not create web-inf directory");

        final File webxml = new File(outputDir, "web.xml");
        final String xmlOut = xml.replace("{{env}}", envName);

        try(FileWriter writer = new FileWriter(webxml)) {
            writer.write(xmlOut);
        }
    }
}
